openhomepy/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from core.views import HomepageView, DiscoveredView, ConnectView

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='dashboard'),
    url(r'discovered/$', DiscoveredView.as_view(), name='discovered'),
    url(r'about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'connect/(?P<pk>\d+)/$', ConnectView.as_view(), name='connect')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

openhomepy/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

core/models.py
from django.db import models

class PhysicalDevice(models.Model):
    device_id = models.CharField(max_length=50, unique=True)

class LogicalDevice(models.Model):
    physical_device = models.ForeignKey(PhysicalDevice, on_delete=models.CASCADE)
    device_id = models.CharField(max_length=50)
    connected = models.BooleanField(default=False)
    device_name = models.CharField(max_length=50)
    device_type = models.CharField(max_length=30)
    device_status = models.TextField()

openhomepy/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

core/forms.py
from django import forms
from .models import LogicalDevice
from django.forms.utils import ErrorList

class ConnectForm(forms.ModelForm):
    class Meta:
        model = LogicalDevice
        exclude = ['device_status', 'connected', 'physical_device', 'device_id', 'device_type']

    def __init__(self, *args, **kwargs):
        super(ConnectForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['device_name'].widget.attrs['autofocus'] = True
            self.fields['device_name'].widget.attrs['class'] = 'form-control'

    def clean(self):
        cleaned_data = super(ConnectForm, self).clean()
        device_name = cleaned_data.get('device_name')
        if LogicalDevice.objects.filter(device_name__iexact=device_name).exclude(pk=self.instance.pk).count() > 0:
            self._errors['device_name'] = ErrorList(['Name Already Exists!'])

        return cleaned_data

core/views.py
from .models import *
from .forms import *
from django.views.generic import ListView, FormView, UpdateView
from django.core.urlresolvers import reverse_lazy


class HomepageView(ListView):
    template_name = 'index.html'
    model = LogicalDevice
    queryset = LogicalDevice.objects.filter(connected=True)
    context_object_name = 'devices'


class DiscoveredView(ListView):
    template_name = 'discovered.html'
    model = PhysicalDevice
    context_object_name = 'devices'


class ConnectView(UpdateView):
    template_name = 'connect.html'
    model = LogicalDevice
    form_class = ConnectForm
    success_url = reverse_lazy('dashboard')

openhomepy/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

openhomepy/templates/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About</h1><br />
    This project is blah blah blah
{% endblock content %}

openhomepy/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>{% block title %}OpenHomePy{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        {% block css %}
        <!-- Your stuff: Third-party css libraries go here -->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
        <!-- This file store project specific CSS -->
        <link href="{% static 'css/project.css' %}" rel="stylesheet">
        {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="pull-left" href="/"><img style="margin:5px;" height="40px" src="{% static 'images/OHPlogo_white.svg' %}"></a>
                </div>
                <div id="navbar" class="collapse navbar-collapse pull-right">
                    <ul class="nav navbar-nav">
                        <li {% if request.resolver_match.url_name == 'dashboard' %} class="active" {% endif %}><a href="{% url 'dashboard' %}">Dashboard</a></li>
                        <li {% if request.resolver_match.url_name == 'discovered' %} class="active" {% endif %}><a href="{% url 'discovered' %}">Discovered Devices</a></li>
                        <li {% if request.resolver_match.url_name == 'about' %} class="active" {% endif %}><a href="{% url 'about' %}">About</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="project-template">
                {% block content %}
                    <p></p>
                {% endblock content %}
            </div>
        </div> <!-- /container -->

        {% block modal %}{% endblock modal %}

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        {% block javascript %}
            <!-- Latest JQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

            <!-- Tether - a requirement for Bootstrap tooltips -->
            <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

            <!-- Latest compiled and minified JavaScript -->
            <!--<script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>-->
            <script src="{% static 'js/bootstrap.min.js' %}"></script>

            <!-- Your stuff: Third-party javascript libraries go here -->

            <!-- place project specific Javascript in this file -->
            <script src="{% static 'js/project.js' %}"></script>
        {% endblock javascript %}

    {% block additional_javascript %}
    {% endblock additional_javascript %}
    </body>
</html>

openhomepy/templates/connect.html
{% extends "base.html" %}
{% block content %}
    <h1>Connect Device</h1><br />
    <form action="" method="post">
        {% csrf_token %}
        <label class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Device ID:</label> {{ form.instance.device_id }}<br /><br />

        <label class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Device Type</label> {{ form.instance.device_type }}<br /><br />

        <label class="col-xs-3 col-sm-3 col-md-3 col-lg-3">Device Name:</label> <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3" style="padding:0;">{{ form.device_name }}</div>
        <div class="clearfix">&nbsp;</div>
        {% for error in form.device_name.errors %}
            <label class="col-xs-3 col-sm-3 col-md-3 col-lg-3">&nbsp;</label>
            <div class="form-group has-error">
                <label class="col-xs-3 col-sm-3 col-md-3 col-lg-3 control-label">{{ error|escape }}</label>
            </div>
        {% endfor %}
        <div class="clearfix">&nbsp;</div>
        <div class="col-xs-5 col-sm-5 col-md-5 col-lg-5" style="padding:0;"><a class="btn btn-secondary pull-right" role="button" href="{% url 'discovered' %}">Cancel</a></div>
        <div class="col-xs-1 col-sm-1 col-md-1 col-lg-1" style="padding:0;"><input class="btn btn-primary pull-right" type="submit" value="Save" /></div>
    </form>

{% endblock content %}

openhomepy/templates/discovered.html
{% extends "base.html" %}
{% block content %}
    <h1>Discovered Devices</h1><br />

    <div class="panel-group">
    {% for pdevice in devices %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title" data-toggle="collapse" href="#collapse{{ forloop.counter }}">
                    <i class="glyphicon glyphicon-chevron-down"></i> &nbsp;{{ pdevice.device_id }}
                </h4>
            </div>
            <div id="collapse{{ forloop.counter }}" class="panel-collapse">
                    <div class="panel-body">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><strong>Device ID</strong></div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><strong>Device Name</strong></div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3"><strong>Device Type</strong></div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">&nbsp;</div>
                    </div>
                {% for ldevice in pdevice.logicaldevice_set.all %}
                    <div class="panel-body vcenter">
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">{{ ldevice.device_id }}</div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">{{ ldevice.device_name }}</div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">{{ ldevice.device_type }}</div>
                        <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3">
                            {% if ldevice.connected %}
                            <a class="btn btn-primary" role="button" href="{% url 'connect' ldevice.id %}">Edit</a>
                            {% else %}
                            <a class="btn btn-primary" role="button" href="{% url 'connect' ldevice.id %}">Connect</a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    </div>





{% endblock content %}

openhomepy/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Connected Devices</h1><br />

    <table class="table table-hover">
        <thead>
            <tr>
                <th>Device</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        {% for device in devices %}
            <tr>
                <td style="vertical-align:middle">{{ device.device_name }}</td>
            {% if device.device_status|lower == 'off' %}
                <td><a href="#" class="btn btn-default btn-lg" role="button"><span class="blink_me"><i style="color:red;font-size:20px;" class="fa fa-fire" aria-hidden="true"></i></span></a></td>
            {% else %}
                <td><a href="#" class="btn btn-default btn-lg" role="button"><i style="color:green;font-size:20px;" class="fa fa-fire" aria-hidden="true"></i></a</td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}

{% block additional_javascript %}
<script type='text/javascript'>//<![CDATA[
    $(function(){
    function blinker() {
        $('.blink_me').fadeOut(500);
        $('.blink_me').fadeIn(500);
    }

    setInterval(blinker, 1000);
    });//]]>
</script>
{% endblock additional_javascript %}

openhomepy/templates/pages/about.html
{% extends "base.html" %}